name: Deploy-Prod🟢

on:
  push:
    branches: 
      - master
jobs:
  build:
    name: 🚀 Deploy to Production
    runs-on: ubuntu-latest
    steps:

      - name: ✅ Checkout
        uses: actions/checkout@v2

      - name: ⌛Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: ➕ Install Deps
        run: python -m pip install --upgrade build twine pytest

      - name: 🧪 Test
        run : python -m pytest -rx

      - name: ⚙️ Build
        run: python -m build

      - name: 🚀 Publish to PyPI
        run: python -m twine upload dist/* -u __token__ -p ${{secrets.PYPI_API_TOKEN}} --verbose             